package com.zongmu.ffmpeg.entities;

public enum AssetFileStatus {
    UPLOADING, UPLOADFAILED,UPLOADSUCCESS, FTPUPLOADING, FTPUPLOADFAILED, FTPUPLOADSUCCESS, COMPRESSING, COMPRESSFAILED, COMPRESSSUCCESS
}
