package com.zongmu.service.dto.asset;

public enum AssetFileStatus {
	UPLOADING, UPLOADFAILED, UPLOADSUCCESS, FTPUPLOADING, FTPUPLOADFAILED, FTPUPLOADSUCCESS, COMPRESSING, COMPRESSFAILED, COMPRESSSUCCESS
}
